// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var num = 2;
var prev = 1;
var sum = 0;

// console.log(prev);

while(num<=4000000){

//   console.log(num);
//Evaluate whether the Fibonacci number is even
  if (num%2==0){
    sum+=num;
  }

  //Exchange values.
  var thisNum = num;//Keep a temporary value for num, to assign it to previus
  num+=prev; //num adds the previous value
  prev = thisNum; 

}

console.log("sum = "+sum);
